spring.application.name=uorderflow

spring.datasource.url=${UORDERFLOW_DB_URL}
spring.datasource.username=${UORDERFLOW_DB_USER}
spring.datasource.password=${UORDERFLOW_DB_PASS}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_batch_fetch_size=100

api.security.token.secret=${UORDERFLOW_JWT_SECRET}

server.error.include-stacktrace=never

